### ISSUE TITLE
Section

### ISSUE THREAD

**Issue by Remy2072** [Jaywesterlow/connect-your-tribe-profile-card#1]
Voor een semantischere html voeg een section en een main om je content heen.
https://github.com/Jaywesterlow/connect-your-tribe-profile-card/blob/main/views/index.ejs
<img width="1792" alt="Scherm­afbeelding 2024-02-09 om 11 24 00" src="https://github.com/Jaywesterlow/connect-your-tribe-profile-card/assets/70781820/ec2e74a5-aa14-44c4-a0a0-2a04c23dc12c">
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/section
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/main

**Comment by Jaywesterlow** [comment]
Dit is niet relevant want ik liet je zien dat het al was gefixed maar je had geen zin om een andere issue te schrijven
